apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: nginx
  labels:
    app: nginx-app
    name: nginx
  annotations:
    "lbipam.cilium.io/ips": "192.168.0.99"
spec:
  type: LoadBalancer
  ports:
  - name: nginx-port
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx
